### ISSUE TITLE
Can't hide menu drawer after set drawer to false

### ISSUE THREAD

**Issue by ganjarsetia** [kingyue737/vitify-next#4]
After I clone & install dependency then I change this line

https://github.com/kingyue737/vitify-next/blob/92a4ada5645f9b2b69c7215566149ab3cc918784/src/stores/app.ts#L6

to `drawer: false, ` then open it in Chrome Incognito, the drawer still showing. The menu drawer should hide.

![image](https://github.com/user-attachments/assets/7943e85c-2626-448f-9bc9-ff142563c6f1)

also there is 2 problem:

1. When you change screen size to mobile responsive then back again to desktop, the drawer hide automatically. It should show like the last state. To try this make sure  set `drawer: true, ` 
2. The image logo is cropped in responsive mode. You can see below

![image](https://github.com/user-attachments/assets/d769eb7a-8cc3-475f-b29d-7e4822e50ea0)

Additional info:
I run on PC using Linux, my screen width is 1360

**Comment by kingyue737** [comment]
Firstly, thanks for using this template!

> When you change screen size to mobile responsive then back again to desktop

I don't see the point of doing this, your mobile phone won't suddenly become a laptop in real life.

>to drawer: false,  then open it in Chrome Incognito, the drawer still showing. The menu drawer should hide.

Expected behavior for me because I want the drawer to show or hide according to the viewport width. If you want the drawer hidden on startup, You can remove the following line:

https://github.com/kingyue737/vitify-next/blob/92a4ada5645f9b2b69c7215566149ab3cc918784/src/components/layout/AppDrawer.vue#L19

Since this is an **opinionated** template, you can alter anything on your side. It may not be 'should' on my side so I won't fix it here. However, you are always welcome to post questions if you don't know how to modify the template to meet your needs.

**Comment by ganjarsetia** [comment]
Thanks for your reply :smiley: 

> I don't see the point of doing this, your mobile phone won't suddenly become a laptop in real life.

Its DX things like when you test responsive. Its fine if you dont give me solution to that, its optional

> Since this is an opinionated template, you can alter anything on your side. It may not be 'should' on my side so I won't fix it here. However, you are always welcome to post questions if you don't know how to modify the template to meet your needs.

Sorry my English is not good. Now I understand what the meaning of "opinionated template". If its like that, my suggestion is better disabling Github issue, but its up to you

Thanks again :grin:
